---
title: "2019-4-17"
author: "ailien"
date: "2019年4月17日"
output: html_document
---

6.3 Recursive objects

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
length(studentRecord)
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

[[.]]
```{r}
plasticContainer
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

```{r}
plasticContainer[["blueBox"]]
plasticContainer[["redBox"]]
```

Q:greenBox包含兩個元素：paper, scissor。如果上面要取出paper，要怎麼延伸拿取？
```{r}
plasticContainer[["greenBox"]] 
plasticContainer[["greenBox"]] 
plasticContainer[["greenBox"]][[1]]
```

```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```

Q:請取出前面成績單物件的個經元素。

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單[["個經"]]#方法一
成績單[[1]]
成績單[["個經"]][[1]]#方法二
```

Q:針對studentRecord物件:

請取出姓名元素。
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
studentRecord[["姓名"]]
```

請取出三年級學年平均成績。

```{r}
studentRecord[["學年平均成績"]][["三年級"]]
```

#6.4.2 [.] extraction

```{r}
plasticContainer
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```

```{r}
plasticContainer

extract1<- plasticContainer[c("greenBox")] 
extract1
extract2<- plasticContainer[[c("greenBox")]]
extract2
plasticContainer[c(1,2)]
```

Q:請各自由extract1及extract2取出“paper”元素值。

```{r}
plasticContainer

extract1 <- plasticContainer[c("greenBox")]
extract1[[1]][[1]]
extract2 <- plasticContainer[[c("greenBox")]]
extract2[[1]]
```

```{r}
plasticContainer

length(plasticContainer)
plasticContainer[c(T,F,T)]
```

```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```

```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```

#6.4.3 $. extraction
```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```
6.4.4 範例：Github commit記錄
```{r}
your_github_username <- "ailienchen"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```

```{r}

```

#6.4.6 範例：str_split
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

```{r}
filmVotingData$Timestamp
filmVotingData[["Timestamp"]]
filmVotingData`Timestamp`
```

Q:birthday只能有8位元，str_length()可計算每個元素的位元長度。請產生一個logical vector稱為logiCorrect，TRUE表示剛好8位元。
```{r}
filmVotingData[["birthday"]]
str_length("birthday")
logiCorrect <- str_length(birthday)==8
logiCorrect
```

Q:只留下birthday輸入正確的人，請統計各別片名支持人數。
```{r}
favoriteTwo[logiCorrect]->validfavoriteTwo
```




























