---
title: "2019-06-18 midtern2"
author: "ailien"
date: "2019年6月18日"
output: html_document
---

```{r}
library(lubridate); library(stringr); library(purrr); library(readr);
```

2.

```{r}
chrNumber<-c("10","25","11")
12->criticalNumber
chrNumber
criticalNumber
```
```{r}
as.numeric(chrNumber)->numNumber# 將character物件chrNumber轉成numeric物件numNumber
numNumber
chrNumber
```
```{r}
logiTrue <- numNumber <= criticalNumber # numNumber中小於等於criticalNumber的元素logic判斷值
numNumber
logiTrue 
```

```{r}
max(numNumber[logiTrue]) -> maxNum # 自numNumber中取出logiTrue為TRUE的值，找出當中最大的存在maxNum
numNumber
numNumber[logiTrue]
max(numNumber[logiTrue])
```

```{r}
str_smallClosest <- function(chrNumber,criticalNumber){
  as.numeric(chrNumber) -> numNumber # 將character物件chrNumber轉成numeric物件numNumber
  logiTrue <- numNumber <= criticalNumber # numNumber中小於等於criticalNumber的元素logic判斷值
  max(numNumber[logiTrue]) -> maxNum # 自numNumber中取出logiTrue為TRUE的值，找出當中最大的存在maxNum
  return(as.character(maxNum)) # 將maxNum轉成character回傳
}

str_smallClosest
```

```{r}
str_smallClosest(c("105","101","99"),100)
```

3.1
```{r}
EconCourseSelectionInfo <- list(
    "101"=list(
      url="http://www.econ.ntpu.edu.tw/econ/files/Way/2016072195021.doc"
    ),
    "104"=list(
      url="http://www.econ.ntpu.edu.tw/econ/files/Way/2016072195041.doc"
    ),
    "105"=list(
      url="http://www.econ.ntpu.edu.tw/econ/files/Way/20170516144353.doc"
    ),
    "107"=list(
      url="http://www.econ.ntpu.edu.tw/econ/files/Way/20180518121643.pdf"
    )
  )

EconCourseSelectionInfo
```

```{r}
EconCourseSelectionInfo[["104"]]$url
```

3.2

```{r}
if(entranceYear %in% c(101,102,103)){#適用101文件的條件:entranceYear 101,102,103
  output <-EconCourseSelectionInfo[["101"]]&url
} else if (entranceYear==104){#適用104文件的條件:entranceYear 104
  output <-EconCourseSelectionInfo[["104"]]&url
} else if (entranceYear %in% c(105,106)){ #適用105文件的條件:entranceYear 105 106
  output <-EconCourseSelectionInfo[["105"]]&url
} else if (entranceYear>=107){#適用106文件的條件:entranceYear>=107
  output <-EconCourseSelectionInfo[["107"]]&url
} else  {#entrance< 101 沒答案，要找系辦
  output <- "很抱歉沒有您入學年的資訊，請打系辦電話"
}
```




```{r}
search_courseRules <- function(entranceYear,EconCourseSelectionInfo){
  if(entranceYear %in% c(101,102,103)){#適用101文件的條件:entranceYear 101,102,103
  output <-EconCourseSelectionInfo[["101"]]&url
} else if (entranceYear==104){#適用104文件的條件:entranceYear 104
  output <-EconCourseSelectionInfo[["104"]]&url
} else if (entranceYear %in% c(105,106)){ #適用105文件的條件:entranceYear 105 106
  output <-EconCourseSelectionInfo[["105"]]&url
} else if (entranceYear>=107){#適用106文件的條件:entranceYear>=107
  output <-EconCourseSelectionInfo[["107"]]&url
} else  {#entrance< 101 沒答案，要找系辦
  output <- "很抱歉沒有您入學年的資訊，請打系辦電話"
}
  retur(output)
}

search_courseRules
```

3.3
search_courseRules_flexible(entranceYear,courseSelectionInfo)

```{r}
#設定測試input值
courseSelectionInfo<-EconCourseSelectionInfo
#1.從courseSelectionInfo可知道文件頒布年分
names(EconCourseSelectionInfo)->ruleYears
ruleYears
#2.再從這些文件學年找出哪些是在entranceYear之前頒布的
as.numeric(ruleYears)->numNumber
entranceYear<-c("101","102","103","104")
numNumber <= entranceYear -> logiTrue
if(any(logiTrue)){
#3.符合上述條件的文件裡，選出頒布學年最近的一份回傳url
#numNumber[logiTrue]#符合上述條件的文件學年
max(numNumber[logiTrue])->maxNum

courseSelectionInfo[[as.character(maxNum)]]$url->output
}else{
  output<-"很抱歉沒有您入學年的資訊，請打系辦電話"
}
```

```{r}
search_courseRules_flexible<-function(entranceYear,courseSelectionInfo){
  #設定測試input值
  courseSelectionInfo<-EconCourseSelectionInfo
  #1.從courseSelectionInfo可知道文件頒布年分
  names(EconCourseSelectionInfo)->ruleYears
  ruleYears
  #2.再從這些文件學年找出哪些是在entranceYear之前頒布的
  as.numeric(ruleYears)->numNumber
  entranceYear<-c("101","102","103","104")
  numNumber <= entranceYear -> logiTrue
  if(any(logiTrue)){
  #3.符合上述條件的文件裡，選出頒布學年最近的一份回傳url
  #numNumber[logiTrue]#符合上述條件的文件學年
  max(numNumber[logiTrue])->maxNum

  courseSelectionInfo[[as.character(maxNum)]]$url->output
  }else{
  output<-"很抱歉沒有您入學年的資訊，請打系辦電話"
}
}
```


```{r}
search_courseRules_flexible(102,EconCourseSelectionInfo)
```



```{r}
search_courseRules_flexible <- function(entranceYear,courseSelectionInfo){
  names(courseSelectionInfo) -> ruleYears
  ## 以下借用第2題答案但小修改
  as.numeric(ruleYears) -> numNumber
  logiTrue <- numNumber <= as.numeric(entranceYear)
  if(any(logiTrue)){
    max(numNumber[logiTrue]) -> maxNum
    return(courseSelectionInfo[[as.character(maxNum)]]$url)
  } else {
    return("很抱歉沒有您入學年的資訊，請打系辦電話")
  }
}

search_courseRules_flexible
```

```{r}
search_courseRules_flexible(102,EconCourseSelectionInfo)
```


