---
title: '2019-05-15'
author: "ailien"
date: "2019年5月15日"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

names():

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

## colnames/rownames

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2)<-c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```

只改col2
```{r}
colnames(StuDF2)[[2]]<-c("姓名")
colnames(StuDF2)
StuDF2
```

改col2,col3的名稱
```{r}
colnames(StuDF2)[c(2,3)]<-c("name","grade")
colnames(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2)[c(1,2,3)]<-c("numbers","name","grade")
colnames(StuDF2)
StuDF2
```

```{r}
rownames(StuDF2)[c(1,2,3,4,5)]<-c("one","two","three","four","five")
rownames(StuDF2)
StuDF2
```


```{r}
library(stringr)

```

7.6 新增/替換元素

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a
a[[5]] <- "7" # 元素不存在
a
```

請將下面的TRUE換成FALSE, 並增加第5個元素其值為數字7。

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```

```{r}
b[[3]]<-"False"
b[[5]]<-"7"
b
```

```{r}
b$元素3<-"False"
b$元素5<-"7"
b
```

使用"元素名稱"創新元素

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

期中考6.2







```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

取出「期間」變數轉成date class。
```{r}
library(lubridate)
exData3$期間<-ymd(exData3$期間)
class(exData3$期間)
```

```{r}
library(lubridate)
ymd(exData3$期間) -> A
class(A)
```

增加一個「isAsiaCrisis」的logical變數，其值為TRUE若「期間」介於1997-06-01到1998-12-01（含前後）。

```{r}
isAsiaCrisis <- (exData3$期間 >= "1997-06-01" & exData3$期間 <= "1998-12-01")
isAsiaCrisis
```

利用「isAsiaCrisis」值，結合使用[.R,.C]取出1997-06-01到1998-12-01亞洲金融危機的子樣本。

```{r}
logiAsiaCrisis<-exData3$isAsiaCrsis
exData3[logiAsiaCrisis,]
```
或合寫在一起

```{r}
exData3[exData3$isAsiaCrisis==T,]
```



