---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r}
b<-"你好"
```

```{r}
bVector<-c("你好","How are you?")
```

```{r}
class(bVector)
```
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```


```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```
小明說：'明天不用上課。'
小花說：'真的嗎？'

#Logical

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
sum(aLogical)
```

#Factor

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
typeof(studentMajors)
```
```{r}
studentMajor0
```


```{r}
levels(studentMajors)
```

```{r}
studentMajors
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算

trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```


```{r}
birthplace <- factor(c("台北市","台中市")
)
levels(birthplace)
class(birthplace)
typeof(birthplace)
as.integer(birthplace)
```

```{r}
birthplace <- factor(c('台中','台中','台北','台北','台北'))
birthplace
as.integer(birthplace)
```

```{r}
as.integer(studentMajors)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```
```{r}
stringInteger
trueInteger
```

#Date Time


```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 

```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
dtObject<-ymd_hms("2019-03-20 15:00:30")
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

你要如何顯示電腦儲存的秒數內容呢？

```{r}
typeof(dtObject)
```

```{r}
typeof(dtObject)
levels(dtObject)
as.double(dtObject)
```

```{r}
Sys.timezone()
```

```{r}
library(lubridate)
dtObject<-ymd_hms("2019-03-20 16:58:53") 
dtObject<-ymd_hms(c("2019-03-20 16:58:53"))
class(dtObject)
typeof(dtObject)
as.double(dtObject)
```

