---
title: '2019-05-29'
author: "ailien"
date: "2019年5月29日"
output: html_document
---
8.1.3 return與input
```{r}
library(lubridate)

now2<- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
#沒有定義return
```

```{r}
browseURL("https://www.ntpu.edu.tw")
```

```{r}
textbookURL<-function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/")
}
textbookURL()
```

8.1.4 多個output值

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```




```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]#以list的方式呈現
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```

Q:創造一個demand_supply_fun(P,a,b,c,d)，它會輸出一個list包含三個元素：供給量，需求量，超額供給量

```{r}
demand_supply_fun<-function(P,a,b,c,d){
  Qs<- a+b*P
  Qd<- c-d*P
  return(
  list(
      供給量=Qs,
      需求量=Qd,
      超額供給量=Qs-Qd
    )
  )
}
```

```{r}
demand_supply_fun <- function(P,a,b,c,d){
 Qs <- a+b*P
 Qd <- c-d*P
 return(
  list(
    供給量 = Qs,
    需求量 = Qd,
    超額供給 = Qs- Qd
  )
 )
}
```


8.2 依條件執行
8.2.1 
用法一
```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```

```{r}
a<-0
b<-1
supply_fun <- function(P,a,b){
  Qs <- a+b*P
  return(Qs)
}
supply_fun(P=-1,0,1)
```

```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```

8.2.2 
用法二

```{r}
a <-  readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
} else {
  print("a不為負值")
}
```


```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)->yy
supply_fun3(P=2,0,1)
```

修改範例2的gpa_fun, 若輸入學號不存在則在螢幕顯示“查無此學號”。

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]#以list的方式呈現
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```



```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID %in% transcriptDataFinal$學號){
  return(GPA)
  }else{
      message("查無此學號")
    }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```


```{r}

```

範例7

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P必需大於等於",-a/b,"(即-a/b值)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
5%%3
```


```{r}
fizzbuzz<-function(input){
  zeroRemBy3<- input%%3==0
  zeroRemBy5<- input%%5==0
  if{}

}
```

```{r}
fizzbuzz<-function(x){
  if(x%%3==0&x%%5!=0){
    print("fizz")
  }
  else if(x%%5==0&x%%3!=0){
    print("buzz")
  }
  else if(x%%5==0&x%%3==0){
    print("fizzbuzz")
  }
  else{
    print(x)
  }
}
fizzbuzz(20)
```

```{r}
fizzbuzz <- function(number){
  if(number %% 15== 0){ #15要先寫
    return("fizzbuzz")}
    else if(number%% 3 ==0){
      return("fizz")
    }else if (number%% 5 == 0){
      return("buzz")
    }else {
      return(number)
    }
  }
fizzbuzz(20)
```

## any all

```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
```

```{r}
if(a>2) {
  print("a大於2")
}
```

any()或all()將logical vector變成一個logical值

```{r}
if(all(a>2)) {
  print("a大於2")
}
```

8.3 Environment

```{r}
a <- 3

testfun <- function(x){
  y <- a/4
  output <- x*y
  return(output)
}

testfun(2)#called 

a <- 4
testfun(2)
```


