---
title: '2019-06-12'
author: "ailien"
date: "2019年6月12日"
output: html_document
---


```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
studentIds5 <- studentIds[1:5] # 前5筆學號
```

```{r}
studentIds5
```
## body
```{r}
i <- 1
print(studentIds5[[i]])#body
```
##for loop
```{r}
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

#範例一
任務:針對studentIds5裡的每一個學號進行print()

```{r}

```



#範例2

任務：一一檢查gmailAddress每個元素，若沒有寫“@gmail.com”則加上。
##sequence source
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

##body

```{r}
##body
# 開始設定
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
cat("起始狀況\n")
gmailAddress

library(stringr)
# for loop
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}

cat("修正後狀況\n")
gmailAddress
```

練習

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

任務0：print「每個」commit的author等於committer的邏輯判斷結果。

sequence source
```{r}
commitHistory
```

body

```{r}
i <- 1

(commitHistory[[i]][["commit"]][["author"]][["name"]]==commitHistory[[i]][["commit"]][["committer"]][["name"]]) -> logiResult
print(logiResult)
```

for loop

```{r}
for(i in seq_along(commitHistory)){
  (commitHistory[[i]][["commit"]][["author"]][["name"]]==
     commitHistory[[i]][["commit"]][["committer"]][["name"]]) ->
    logiResult
  print(logiResult)  
}
```


```{r}
i <- 1
print(commitHistory[[i]][["commit"]][["author"]][["names"]])
```

##for loop

```{r}
for(i in seq_along(commitHistory)){
  print(commitHistory[[i]][["commit"]][["author"]][["name"]])
}
```


```{r}

```
任務一：存下來每個commit的author。
任務二：存下來每個commit的committer
任務三：存下來每個author與committer同人的commitDate

```{r}

```


```{r}
for(i in seq_along(commitHistory)){
  print(
    str_c(
      "Author is ",
      commitHistory[[i]][["commit"]][["author"]][["name"]],
      ". Committer is ",
      commitHistory[[i]][["commit"]][["committer"]][["name"]]
      )
    )
}
```

