---
title: "2019-04-24"
author: "ailien"
date: "2019年4月24日"
output: html_document
---
#Matrix
```{r}
Vec1<-c(1:6)
Vec1
```

```{r}
Mat1<- matrix(
  c(1:6),2,3
)
Mat1
```

```{r}
class(Mat1)
```

```{r}
typeof(Mat1)
```

object extraction

```{r}
Mat1
Mat1[[2]]
```



```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
```

Q:
```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
```



#Data Frame

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList
```


```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF)
typeof(StuDF)
```


```{r}
class(StuDF$姓名)
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
StuDF2<- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors=FALSE
  )
StuDF2
```



Q:以list的角度取出胖虎的資料
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF[["姓名"]][[3]]
```

```{r}
class(StuList)
```

```{r}
as.data.frame(StuList) -> StuDF3

class(StuDF3)
```

```{r}
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```

```{r}
StuDF4
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
class(StuDF)
typeof(StuDF)
```
#[.R , .C] object extraction
```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```

```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
m
```



```{r}
chosenLETTERS[8]

```

```{r}
matObj1
```
```{r}
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```

```{r}
matObj1
matObj1[c(1,4),c(2,3)]
```
以邏輯向量表達:
```{r}
matObj1[c(T,F,F,T,F),c(F,T,T)]
```


Q:若只用[.] extraction, 如何取出matObj1[c(1,5),c(2,3)]的元素值？
```{r}

```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
class(classSurvey)
```
Q:請取出性別及本學期學分數。
從data frame視覺角度
```{r}
classSurvey[c(1:60),c(4,5)]
classSurvey[,c(4,5)]
```
從R的角度(即單純list的角度)
```{r}
# classSurvey[]
classSurvey[c("性別","本學期學分數")]

```

子樣本

```{r}
classSurvey[logical_index,]
```









```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

